### ISSUE TITLE
Review analytic processors and determine the data structures needed to each chart or chart/analytic pair

### ISSUE THREAD

**Issue by jeffshaver** [jeffshaver/safe-app#80]
The basic idea is that we need to take a look at each analytic processor in order to determine the format for the data that the rest api should send to the client.

@pml984 has been working on changing us over to a new chart library, so he will have insights as to what formats we are expecting for each chart.

Jenn and Savannah will both understand the processors and Savannah will be the one (probably) working on outputting the correct formats.

**Comment by jpkeyw** [comment]
Looping @sdurbin1 in on the conversation this afternoon....

**Comment by cafedavid** [comment]
as of now, we will be providing the REST api a single visualization id and the server will handle everything regarding analytic processors. 

however, what jen needs now is complete documentation for what data she is expected to return from the REST api for each visualization object (e.g., for a visualization-type: pie, what json should she send back?). 

assigning to @pml984 due to authoring of safe-framework visualization components.
