### ISSUE TITLE
Some reducers not included in modules/index.js combineReducers

### ISSUE THREAD

**Issue by jpkeyw** [jeffshaver/safe-app#92]
including `createDashboard`, `deleteDashboard`, `editDashboard`. But, check for others, too.

**Comment by jeffshaver** [comment]
The way this basically ended up hapening is that `createDashboard`, `deleteDashboard` and `editDashboard` originally didn't have reducers. They originally only had async actions. However with #85, I added a reducer so that their async failure states could be tracked.

Easy task. Just add them into `modules/index.js`
